### ISSUE TITLE
INSTALL file not complete

### ISSUE THREAD

**Issue by jdkloe** [stcorp/coda#1]
The coda sources as provided on github do not contain the configure script as mentioned in the INSTALL file. Therefore, if a user wishes to install the coda from sources cloned from github some extra instructions are needed, i.e. the autotools should be applied first.
For example these commands worked in my Fedora linux system:
```
ln -s ./config.h.cmake.in config.h.in
libtoolize
aclocal
autoconf
automake -a

./configure --enable-python --prefix=`pwd`/../coda_install --with-hdf5
make
make install
```
I think it would be good to add some instructions to the INSTALL file to explain this.

**Comment by svniemeijer** [comment]
There is a bootstrap script that will do this for you. Please use that.
We will add this to the INSTALL file, but we still recommend you use the official source package that can be found as download for each release in github as well.

Also, copying config.h.cmake.in to config.h.in is definitely incorrect and will give you build problems.

**Comment by jdkloe** [comment]
thanks, the bootstrap script works fine for me.

**Comment by svniemeijer** [comment]
github instructions have been added to the INSTALL file in v2.16
