### ISSUE TITLE
Does CODA still use the HDF4 netCDF API, and in which case?

### ISSUE THREAD

**Issue by OkoSanto** [stcorp/coda#16]
Hi,

the INSTALL document states:

>   - If you want to use the HDF4 features of CODA then you will need to have a
    recent version of HDF4 installed (for building the source package on
    Windows you will need to have version 4.2.11 of HDF).
    You will also need the additional required libraries libjpeg, szlib, and
    zlib.
    On some UNIX systems you can install HDF4 via the package manager on your
    system. Make sure that this package also installs the netcdf.h include file
    on your system. If this is not the case you will also have to install the
    netcdf package on your system.

Is the part about netcdf.h still up to date?  I have installed coda using --with-hdf4, but linking against a HDF4 library that does not contain netcdf.h (HDF4 configured with --disable-netcdf), in an environment without netCDF package.  Still, it seems to work (I could open an HDF4 file and read the names of some groups in the file).

**Comment by svniemeijer** [comment]
That comment is indeed no longer applicable. We will rephrase this section and remove the requirement on needing netcdf.h
