### ISSUE TITLE
What are the minimum version of compilers for coda?

### ISSUE THREAD

**Issue by schwehr** [stcorp/coda#38]
Documentation request:

This impacts changes that I'd like send to coda.  Does coda really need to support compilers older than 8 years (e.g. if it's Visual Studio >= 2012 or newer, gcc >= ?, clang >= ?, mingw >= ?) that changes what the code has to do.

e.g. for my local build (with bazel and clang/llvm), I have to remove a swath of coda.h and replace it with just `#include <stdint.h>` (without a surrounding #ifdef HAVE_STDINT_H).  I'm happy to share that change if it doesn't break the requirements of coda.  e.g. In my local code, I can assume that stdint.h works and I'm wondering your assumptions.  

And does the code have to be C89 or can C99 features be used?  I presume you don't support and C11 features.

- https://en.wikipedia.org/wiki/List_of_compilers#C_compilers
- https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#History
- http://mingw-w64.org/doku.php/versions
- https://gcc.gnu.org/releases.html
- https://en.wikipedia.org/wiki/Clang

**Comment by svniemeijer** [comment]
Closing this issue as there is no immediate action to take.
