### ISSUE TITLE
coda_fetch

### ISSUE THREAD

**Issue by sahar-github** [stcorp/coda#87]
I used coda_fetch for one data in matlab and it worked, but if I try to use it with completely similar data type only from another date, it does not work anymore. I get an error message like:
ERROR : product error detected (value for ascii integer too large for uint16)
Error using coda_matlab
CODA Error
Error in coda_fetch (line 25)
[varargout{1:max(1,nargout)}] = coda_matlab('FETCH',varargin{:});

could you please help me how can i solve this issue?
Thanks

**Comment by svniemeijer** [comment]
What product are you trying to read? (please make sure you give sufficient information, otherwise we can't help)

**Comment by svniemeijer** [comment]
Please provide the _exact_ product name of the product that is giving this problem
