### ISSUE TITLE
can not fetch data coda_fetch MATLAB interface: error for unit16

### ISSUE THREAD

**Issue by sahar-github** [stcorp/coda#89]
I am trying to read some data from different but similar sensors. My code is working for the first sensor but as soon as I run the routine for the second data, I get the below error message from the coda_fetch (matlab interface)
Could you please guide me how to resolve this issue?
Thanks
**%%%%%%%%%%%Error Message%%%%%%%%%%%%%%%%%%%%%%%**
ERROR : product error detected (value for ascii integer too large for uint16)
Error using coda_matlab
CODA Error

Error in coda_fetch (line 25)
[varargout{1:max(1,nargout)}] = coda_matlab('FETCH',varargin{:});

**Comment by sahar-github** [comment]
the strange thing is that If I use the coda python interface instead of matlab interface, I face no problem any more and can easily open the dataset

**Comment by svniemeijer** [comment]
You are probably using the wrong codadef file with your matlab coda installation. Can you let me know where you installed coda (for your matlab interface), what product you are trying to read, and which codadef files you installed (and where)?

**Comment by sahar-github** [comment]
I am using  exactly the same codadef file for both matlab and python. 
I installed the coda in my user space (home/bin/Coda/lib64/coda/matlab)
I am trying to read IASI data (I can read IASI-B data but not IASI-A data with the same matlab interface) 
I installed my codadef file here:
/tcenas/home/bin/Coda/share/coda/definitions/
and the codadef file that I am using is
EPS-20190617.codadef

and here is the link to the data that I can read with Python interface but not with the matlab interface: 
https://we.tl/t-S0etdHIGyy

thanks!

**Comment by svniemeijer** [comment]
Could you try the latest codadef? https://github.com/stcorp/codadef-eps/releases/tag/20210313
