### ISSUE TITLE
Move to pcre2

### ISSUE THREAD

**Issue by bgermann** [stcorp/coda#97]
coda was removed from Debian testing because it [depends on the end-of-life PCRE library](https://bugs.debian.org/1000090).
The newer PCRE2 library (the official successor to PCRE) was first released in 2015.
Upstream's documentation for PCRE2 is available here: https://pcre.org/current/doc/html/

Please consider updating to PCRE2.

**Comment by svniemeijer** [comment]
Sounds like a good idea. We will investigate.

**Comment by svniemeijer** [comment]
This was implemented in CODA V2.25.
